bindPort = 45045

auth.method = "token"
auth.token = "test-frp-token-8a5e"

webServer.addr = "0.0.0.0"
webServer.port = 19780
webServer.user = "admin"
webServer.password = "admin"

allowPorts = [{ start = 35000, end = 35020 }]

log.to = "D:/VCPHub/VCPDeck/.tmp/frp-test-1785051001262/frps.log"
log.level = "info"
log.maxDays = 1