bindPort = 17000
auth.method = "token"
auth.token = "test123"
webServer.addr = "0.0.0.0"
webServer.port = 17500
webServer.user = "admin"
webServer.password = "admin"
allowPorts = [{ start = 30000, end = 30010 }]
log.to = "./frps.log"
log.level = "info"
log.maxDays = 1
